#!/bin/sh
##This script will install Jenkins on Ubuntu server...

#Update software repositories and install Java
sudo apt update -y
sudo apt install default-jdk -y

echo Adding the repository key to your system...
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

#The command below will add the Debian package repository address to /etc/apt/sources.list.d/jenkins.list
sudo echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

#The command below will enable "apt" to use the new repository.
sudo apt update -y

#The command below will install jenkins and all the required dependencies.
sudo apt install jenkins -y

#Check the status of your installation
sudo systemctl start jenkins
sudo systemctl status jenkins

#Ensure that port 8080 is open on the firewall to access jenkins
