#!/bin/sh
echo This installation script will install Nexus
echo To install Nexus, Java and other applications that will aid will be installed 
echo Have you created a RedHat AWS server that has 4gb RAM or more? 
echo Enter 1 for yes and 2 for no.
read response
if
        (( $response == 1 ))
then
        echo Let us start by adding nexus as user
        sudo adduser nexus
        sleep 1
        echo nexus has been successfully added
        echo Enter a password
        read -s password
        sleep 1
        echo $password | sudo passwd nexus --stdin
        echo Granting sudo powers to nexus...
        sleep 1
        sudo echo "nexus ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/nexus
        echo Enabling password authentication...
        sleep 1
        sudo sed -i "/^[^#]*PasswordAuthentication[[:space:]]no/c\PasswordAuthentication yes" /etc/ssh/sshd_config
        echo Restarting sshd to activate password authentication...
        sleep 1
        sudo systemctl restart sshd
        echo Updating hostname...
        sudo hostname nexus
        echo Changing directories for apps installation...
        cd /opt
        echo Installing apps to get us running...
        sudo yum install wget vim nano tree unzip git-all -y
        echo Installing java...
        sudo yum install java-11-openjdk-devel java-1.8.0-openjdk-devel -y
        sleep 1
        java -version
        echo Nexus software installation will start in a moment...
        sleep 1
        sudo wget http://download.sonatype.com/nexus/3/nexus-3.15.2-01-unix.tar.gz
        echo Unzipping to start in a moment...
        sleep 1
        sudo tar -zxvf nexus-3.15.2-01-unix.tar.gz
        echo Deleting the zip file...
        sleep 1
        sudo rm -rfv nexus-3.15.2-01-unix.tar.gz
        echo Renaming the installation directory...
        sleep 1
        sudo mv /opt/nexus-3.15.2-01 /opt/nexus
        echo Changing permissions for /opt/nexus and /opt/sonatype-work directories...
        sleep 1
        sudo chown -R $(whoami):$(whoami) /opt/nexus
        sudo chown -R $(whoami):$(whoami) /opt/sonatype-work
        sudo chmod -R 775 /opt/nexus
        sudo chmod -R 775 /opt/sonatype-work
        echo Updating the nexus.rc file...
        sleep 1
        echo "run_as_user="nexus"" >> /opt/nexus/bin/nexus.rc
        echo Configuring nexus to run as a service...
        sleep 1
        sudo ln -s /opt/nexus/bin/nexus /etc/init.d/nexus
        echo Updating permissions for /opt/nexus and /opt/sonatype-work directories...
        sleep 1
        sudo chown -R nexus:nexus /opt/nexus
        sudo chown -R nexus:nexus /opt/sonatype-work
        sudo su nexus
        echo Enabling, starting and checking the status of the the nexus services...
        sudo systemctl enable nexus
        sudo systemctl start nexus
        sudo systemctl status nexus
        echo The default nexus login details are ADMIN and ADMIN123 for userName and Password respectively.
else
        echo You will need to set up an AWS server with a minimum of 4GB RAM.
fi
