#!/bin/sh
echo This installation will work with Red Hat instance
echo Do you want to continue with your Terraform Installation?
echo Enter 1 for yes and 2 for no.
read response
if
        (( $response == 1 ))
then
        echo Awesome! Your installations will resume shortly...
        ##It is important that you upgrade your system and packages
        #echo Upgrading sytem and packages...
        #sudo yum update -y
        ##Install vim, wget and unzip packages
        echo Installing packages to get us started...
        sudo yum install vim wget unzip -y
        ##Use https://www.terraform.io/downloads.html to ascertain the version to download.
        echo Downloading the terraform software...
        sudo wget https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip
        ##Extract the terraform software into the bin directory.
        echo Extracting the terraform software into the bin directory...
        sudo unzip terraform_1.2.5_linux_amd64.zip -d /usr/local/bin/
        ##Check the version of terraform installed using terraform -v (OR) terraform version
        terraform -v
        echo Displaying the commands that can be used on terraform
        terraform -help
 else
        echo You may check back when you are ready to install the terraform package.
fi       
