#!/bin/sh
echo It is advisable that you do not use the same server for your build and web app deployment.
echo You will need to add security group and open port 8080 with source set at 0.0.0.0/0.
echo Do you want to continue with your Tomcat Installation?
echo Enter 1 for yes and 2 for no.
read response
if
        (( $response == 1 ))
then
        echo Awesome! Your installations will resume shortly...
        sleep 1
        cd /opt
        echo Installing apps to get us running...
        sudo yum install wget vim tree unzip -y
        echo Installing java...
        sudo yum install java-1.8.0-openjdk-devel -y
        sleep 1
        java -version
        sleep 1
        echo Installing Tomcat...
        sleep 1
        sudo wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.tar.gz
        echo Unzipping the Tomcat file...
        sudo tar -xvf apache-tomcat-9.0.63.tar.gz
        echo Deleting the zip file...
        sleep 1
        sudo rm apache-tomcat-9.0.63.tar.gz
        echo Renaming the Tomcat home directory...
        sleep 1
        sudo mv apache-tomcat-9.0.63 tomcat9
        echo Changing ownership of the Tomcat home directory...
        sleep 1
        sudo chown -R "$(whoami)":"$(whoami)" tomcat9
        sudo chown -R "$(whoami)":"$(whoami)" /opt/tomcat9/logs
        echo Updating permissions for the Tomcat home directory...
        sleep 1
        sudo chmod 777 -R /opt/tomcat9
        echo Executing the startup.sh script...
        sleep 1
        sudo sh /opt/tomcat9/bin/startup.sh
        echo Making soft links to start and stop tomcat...
        sleep 1
        sudo ln -s /opt/tomcat9/bin/startup.sh /usr/bin/starttomcat
        sudo ln -s /opt/tomcat9/bin/shutdown.sh /usr/bin/stoptomcat
        echo Updating the ownership of the Tomcat home directory...
        sleep 1
        sudo chown -R "$(whoami)":"$(whoami)" tomcat9
        sudo chown -R "$(whoami)":"$(whoami)" /opt/tomcat9/logs
        echo Tomcat will start up in a moment...
        sleep 1
        starttomcat
else
        echo An instance with a 1 GB memory, for example t2.micro,  will be sufficient for this server.
fi
